---
title: "Daten verstehen und kommunizieren"
runningheader: "Daten verstehen und kommunizieren" # only for pdf output
subtitle: "Donnerstag, 10:15 - 12, vonRoll B005, [KSL](https://ksl.unibe.ch/KSL/kurzansicht?2&stammNr=478535&semester=HS2022&lfdNr=0),  [ILIAS](https://ilias.unibe.ch/goto.php?target=crs_2445306&client_id=ilias3_unibe)" # only for html output
author: "Lilla Gurtner - lilla.gurtner@unibe.ch"
date: ""
toc: TRUE
output:
  tufte::tufte_html: 
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
bibliography: My Library.bib
link-citations: no
---

```{r setup1, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(cache.extra = packageVersion('tufte'))
options(htmltools.dir.version = FALSE)

knitr::opts_chunk$set(cache=F,
                      fig.path = 'figs/',
                      cache.path='cache/',
                      warning=F,
                      message=F)



advdate <- function(obj, adv) {
 tmon <- obj + 7*(adv-1) # obj ist definiert in l. 79, hier wird das datum der woche (adv) berechnet
 tfri <- obj + 4 + 7*(adv-1)
 tmon <- format(tmon, format="%m/%d")
 tfri <- format(tfri, format="%m/%d")
 zadv <- sprintf("%02d", adv)
 tmp <- paste("Woche ", zadv,sep='',", ", tmon)
 return(tmp)
}
library(lubridate)
mon <- ymd(20220922)

```


::: {.fullwidth}

<span style="color:red">__KURSVORAUSSETZUNG:__ ein Laptop mit intstalliertem R, RStudio, tidyverse package, der zu jeder Sitzung mitgebracht werden kann. Unbedingt ab der ersten Sitzung mitbringen!!</span>

:::
# Kursbeschreibung

::: {.fullwidth}
Daten sind omnipräsent in unserem Alltag, ob wir sie selbst für Big-Tech erzeugen oder ob sie uns verkauft werden als Grund für politische Entscheidungen. Wie wichtig Kommunikation von Daten sein kann, wurde in der Covid-19-Pandemie mehr als deutlich und auch Erkenntnisse zum Klima-Wandel wollen effektiv und wirksam kommuniziert werden. Mit Daten umgehen zu können ist eine Kernkompetenz. In diesem Proseminar beleuchten wir die verschiedenen Schritte von den Rohdaten zur Kommunikation.

Die Studierenden werden
- Hands-on Daten einlesen, explorieren, plotten
- Lernen, welche Daten am Besten wie dargestellt werden
- Grundsätzliches Wissen erlangen darüber, wie Menschen Daten verstehen / wie man Daten am Besten kommuniziert.


:::

## Proseminar Ablauf


::: {.fullwidth}

In der ersten Hälfte des Semesters werden wir uns eingehend mit dem Umgang mit Daten beschäftigen. Wir lernen Daten in R einzulesen, zu plotten und zu verarbeiten. Danach widmen wir uns spezifischen Datentypen, wie man sie häufig in der psychologischen Forschung antrifft. In der Zweiten Hälfte beleuchten wir verstärkt das Kommunizieren von Daten: wie vermittelt man Zahlen? Was ist bei der Kommuikation von Unsicherheit und Risiken zu beachten? Was sagt die Kognitionspsychologie zu plots? Ausserdem bekommen wir einen Einblick in Storytelling mit Daten von Simon Schmid, selbstständiger Datenjournalist, u.A. tätig für die Republik. 

Die Studierenden leiten die einzelnen Sitzungen. Man kann sich u.A. anhand der Unterlagen im Syllabus darauf vorbereiten. Bitte jeweils eine Woche vor dem Termin mit mir vorbesprechen! Wir werden als Kurs-Output gemeinsam ein R-Markdown dokument erstellen, in dem jede/r einen Beitrag leistet. Mehr dazu in der ersten Sitzung. 

:::
## Proseminar Arbeit

::: {.fullwidth}

__Abgabe-Termin: 9. Januar 2023.__
Parallel zu den Sitzungen sollen die Studierenden an ihrer Proseminar-Arbeit schreiben. Ziel ist, eine Fragestellung/Hypotese zu formulieren und diese anhand von Daten zu beantworten, und zwar einmal so gut wie möglich und einmal so schlecht wie möglich. Die Seminararbeit besteht aus der Hypothese, der Beschreibung der Datenquelle, dem Code für die Datenverarbeitung und den Plots, der best- und schlechtestmöglichsten Antwort auf die Fragestellung. Die Studierenden erhalten Feedback zu ihrer Arbeit.

Bewertungskriterien für die Proseminar-Arbeit:

- ist die Hypothese empirisch überprüfbar? Ist sie falsifizierbar?

- Sind die Datensets geeignet, um die Hypothese zu beantworten? Ist die Wahl der Datensets begründet? 

- Ist der Code für die Analyse durchgehend kommentiert?

- Die Antwort: jeweils max 1 A4 Seite für die state-of-the-art summary und die worst-case-summary. Die Summary richtet sich an ein Layenpublikum. 

- Wird begründet, wie Zahlen in der Summary berichtet werden, sowie in den verwendeten Plots die Wahl der Farben, Achsen, Beschriftunden, geoms etc.?

:::
## Benotung/Bewertung

::: {.fullwidth}

Das Proseminar ist pass-or-fail. Die Studierenden bestehen, wenn sie die Sitzung, für die sie verantwortlich sind, gut vorbereiten und halten, ihren Beitrag zum gemeinsamen Kurs-Output leisten, die Proseminar-Arbeit bis am 9. Januar abgegeben haben und diese die Bewertungskriterien erfüllt. 

:::


# Sitzungen
## **`r advdate(mon, 1)`: Organisation, Motivation**
_Praxis-Teil:_    StackOverflow, iris data-set, minmal reproducable example, RMarkdown, Folder Structure [@Wilson2017]


## **`r advdate(mon, 2)`: Was können wir aus Daten (nicht) lernen?**

_Verantwortlich:_ Susanne  
_Literatur:_    @Jones2019, Kapitel 2  
_Praxis-Teil:_   Daten online finden und in R einlesen (read_csv etc), load directly from code!


##  **`r advdate(mon, 3)`: Daten-Strukturen**

::: {.fullwidth}


_Verantwortlich:_ Marija  
_Literatur:_ @Wickham2014  
_Praxis-Teil:_   Tidy data: pivot_wider, pivot_longer, mutate

:::


##  **`r advdate(mon, 4)`: Daten verarbeiten: was macht Sinn?**



::: {.fullwidth}

<span style="color:red"> Heute müssen die Fragestellungen abgegeben werden!</span>

_Verantwortlich:_ Sara  
_Literatur:_     @Jones2019, Kapitel 3  
_Praxis-Teil:_    Tidy data2: unite, join, group_by, summarize

:::


##  **`r advdate(mon, 5)`: Wahrnehmung und Graphiken**


::: {.fullwidth}
_Verantwortlich:_ Erich, Mona  
_Literatur:_  @Healey2012 (Teil 1, 2, 5); [39 studies on human perception](https://medium.com/@kennelliott/39-studies-about-human-perception-in-30-minutes-4728f9e31a73): (bitte auslassen: treemaps, other visualisations, pictographs and drawings, audiencees, interactive elements)  
_Praxis-Teil:_    ggplot

:::

##  **`r advdate(mon, 6)`: Wahrnehmung und Graphiken II**
::: {.fullwidth}
_Verantwortlich:_ Joy  
_Literatur:_      @Franconeri2021 (bitte auslassen: "visually communicating uncertaninty and risk")  
_Praxis-Teil:_    Change over time (Entwicklungspsychologie, Klimawandel)

:::


##  **`r advdate(mon, 7)`: Numeracy I**

::: {.fullwidth}

Heute müssen müssen die Datensets feststehen, incl. der Operationalisierung.

_Verantwortlich:_ Lino  
_Literatur:_     @Peters2020, Kapitel 1,2  
_Praxis-Teil:_    Verteilungen von Daten (rt-data, Einkommen, mean vs median)

:::


##  **`r advdate(mon, 8)`: Numeracy II**

::: {.fullwidth}

_Verantwortlich:_ Svenja  
_Literatur:_     @Peters2020, Kapitel 3: Reliance on Heuristics and concrete, easy-to-evaluate attributes  
_Praxis-Teil:_   Count Data (accuracy), raincloud-plot

:::


##  **`r advdate(mon, 9)`: Numeracy III**

::: {.fullwidth}

_Verantwortlich:_ Leonie  
_Literatur:_     @Peters2020, Kapitel 4: Feelings and Frames  
_Praxis-Teil:_    Die eigenen Daten verarbeiten

:::

##  **`r advdate(mon, 10)`: Communicating Numbers**


::: {.fullwidth}

_Verantwortlich:_ Bänz  
_Literatur: _ @Peters2020, Kapitel 16; @Heath2022, Appendix: p. 136  
_Praxis-Teil:_    Die eigenen Daten verarbeiten
:::

##  **`r advdate(mon, 11)`: Unsicherheit und Wahrscheinlichkeit (Kognitionspsychologie)**


::: {.fullwidth}

_Verantwortlich:_ Melanie, Benedikt  
_Literatur: _    @VanDerBles2019  
_Praxis-Teil:_    Die eigenen Daten verarbeiten

:::

##  **`r advdate(mon, 12)`: Storytelling mit Daten, Besuch von Simon Schmid**



## **`r advdate(mon, 13)`: Unsicherheit Darstellen**


::: {.fullwidth}

_Verantwortlich:_ Remo   
_Literatur: _    @Padilla2021; @Franconeri2021 (nur: "visually communicating uncertaninty and risk")  
_Praxis-Teil:_    Die eigenen Daten verarbeiten

:::


##  **`r advdate(mon, 14)`: Wrap-up, Fragen, Buffer**


# Hilfreiche Links

[Gapminder teaching material](https://www.gapminder.org/downloads/)
[Vortrag Richard McElreth rethinking III](https://www.youtube.com/watch?v=FdnMWdICdRs&list=PLDcUM9US4XdPz-KxHM4XHt7uUVGWWVSus&index=1)

[Einführung in R von Boris Mayer und Andrew Ellis](https://methodenlehre.github.io/einfuehrung-in-R/)

[cheat cheet rmarkdown](https://raw.githubusercontent.com/rstudio/cheatsheets/main/rmarkdown.pdf)

[cheat sheet tidyverse](https://ugoproto.github.io/ugo_r_doc/pdf/Tidyverse_for_Beginners.pdf)

[cheat sheet ggplot](https://nyu-cdsc.github.io/learningr/assets/data-visualization-2.1.pdf)

[cheat sheet tidyr](https://leadousset.github.io/intro-to-R/cheatsheet_tidy.pdf)

[cheat sheet dplyr](https://raw.githubusercontent.com/rstudio/cheatsheets/main/data-transformation.pdf)

[alle R-Studio cheat sheets](https://www.rstudio.com/resources/cheatsheets/)

[Taxonomie von visualisierungen](https://datavizcatalogue.com/)

[principles of proportional ink](https://clauswilke.com/dataviz/proportional-ink.html)

[Schreibberatung der Uni Bern](https://www.ub.unibe.ch/service/kurse_und_beratung/schreibberatung/index_ger.html#pane1135463)

[more or less podcast](https://www.bbc.co.uk/programmes/p02nrss1/episodes/downloads): Ein englisch-sprachiger kurzer Podcast zu Zahlen in den Medien und was dahinter steckt. UK-lastig, aber spannend.  

[Calling Bullshit: the art of skepticism in a data-driven world](https://www.youtube.com/watch?v=A2OtU5vlR0k): Vorlesung zum Buch

