---
title: Publications
engine: knitr 
toc: true
toc-location: left
toc-title: Publications
editor_options: 
  chunk_output_type: console
---

## Peer-reviewed papers


Aggrey, V., Pedrazzini, S., **Gurtner, L.**, & Moser, S. (2024). What Motivates Individuals or Groups to Engage in Commons Initiatives? A Scoping Review. [[link]](https://doi.org/10.23668/PSYCHARCHIVES.15504)


**Gurtner, L.** M., & Moser, S. (2024). The where, how, and who of mitigating climate change: A targeted research agenda for psychology. Journal of Environmental Psychology, 94, 102250. [[link]](https://doi.org/10.1016/j.jenvp.2024.102250)


Mast, F. W., & **Gurtner, L.** M. (2023). Mental Rotation and Visual Imagery. In F. W. Mast & L. M. Gurtner, Oxford Research Encyclopedia of Psychology. Oxford University Press. [[link]](https://doi.org/10.1093/acrefore/9780190236557.013.776)


**Gurtner, L.** M., Bischof, W. F., & Mast, F. W. (2023). Gaze Restriction and Reactivation of Place-bound Content Drive Eye Movements During Mental Imagery. Journal of Cognition, 6(1): 51, pp. 1–18. [[link]](https://doi.org/10.5334/joc.316)


**Gurtner, L.** M., Hartmann, M., & Mast, F. W. (2021). Eye movements during visual imagery and perception show spatial correspondence but have unique temporal signatures. Cognition, 210, 104597. [[link]](https://doi.org/10.1016/j.cognition.2021.104597)


**Gurtner, L.** M., Bischof, W. F., & Mast, F. W. (2019). Recurrence quantification analysis of eye movements during mental imagery. Journal of Vision, 19(1), 17. [[link]](https://doi.org/10.1167/19.1.17)


Martarelli, C. S., **Gurtner, L.** M., & Mast, F. W. (2015). School-age children show a bias toward fantasy classifications after playing a platform game. Psychology of Popular Media Culture, 4(4), 351–359. [[link]](https://doi.org/10.1037/ppm0000051)


##  Conference contributions

Pedrazzini, Sabina; **Gurtner, Lilla** (June 2024). Navigating Challenges in Commoning Processes: Understanding Individual Dynamics. In: Symposium: What we talk about when we talk about the commons? Leeds. 17 - 18. 06.2024.


**Gurtner, Lilla**; Moser, Stephanie (June 2023). The where to, how and who of mitigating climate change: a targeted research agenda for psychology to support social transitions. In: ICEP Conference. Aarhus. 20-23. 06.2023. 


Moser, Stephanie; **Gurtner, Lilla** (2023). Working time reduction as a moment of change for climate-friendly behaviour? (Unpublished). In: Presentation at the International Conference on Environmental Psychology (ICEP 2023). Aarhus, Denmark. 20-23 June 2023. 


**Gurtner, Lilla**; Bischof, Walter F.; Mast, Fred W. (August 2019). Temporal patterns of eye movements reflect the complexity of a mental image (Unpublished). In: European Conference on Eye Movements. Alicante, Spain. 18.8.-23.8.2019.

##  White papers

Moser, Stephanie; **Gurtner, Lilla**; Bezzola, Nicolà; Neubert, Sebastian (2024). Wohlbefinden und Ökologie durch mehr Zeit? (CDE Working Papers 8). Centre for Development and Environment (CDE), Stiftung Mercator Schweiz, GZO Spital Wetzikon, mit Bern Open Publishing (BOP) 



##  Media contributions

**Gurtner, Lilla**; Moser, Stephanie (2024). Wohin, wie und mit wem in eine bessere Zukunft?. Rethink now. [[link, accessed: 3. May 2024]](https://www.one-planet-lab.ch/post/wohin-wie-und-mit-wem-in-eine-bessere-zukunft)


**Gurtner, Lilla** (2024). Psychologists and Climate Change: What Vision Should Guide Us, and How and With Whom Do We Get There?. Character & Context Blog. [[link, accessed: 10. June 2024]](https://spsp.org/news/character-and-context-blog/gurtner-environmental-psychology-climate-transformation-research?_zs=L2Qne&_zl=Sgr64)


**Gurtner, Lilla** (2024, August). Frau Gurtner, warum reicht die bisherige psychologische Forschung zum Klimawandel nicht aus?. Psychologie Heute. [[link, accessed: 25th of July 2024]](https://www.psychologie-heute.de/gesellschaft/artikel-detailansicht/43550-warum-reicht-die-bisherige-psychologische-forschung-zum-klimawandel-nicht-aus.html)

##  Data publications

**Gurtner, Lilla**; Weber, Enea; Mast, Fred W (2024). Data and analysis of "Eyes still Move when the Mind Is Blind: Content-Related Eye Movements During Mental Imagery in Aphantasia". [[link]](https://doi.org/10.48620/77347)
